[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

remappings = [
    "@uniswap/lib/=lib/solidity-lib/",
    "@uniswap/v2-core/=lib/v2-core/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
